# Generated by Django 2.1.2 on 2018-10-13 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=50, verbose_name='Chr')),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('sequence_id', models.CharField(max_length=50)),
                ('rna_sequence', models.CharField(max_length=35, verbose_name='sequence')),
                ('source', models.CharField(max_length=40)),
                ('development_stage', models.CharField(max_length=50, verbose_name='stage')),
                ('target_gene', models.CharField(max_length=40, verbose_name='target')),
                ('number_mismatches_allowed', models.IntegerField(verbose_name='NM')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=50)),
                ('species_name', models.CharField(max_length=50)),
                ('common_name', models.CharField(max_length=50, null=True)),
                ('icon', models.FileField(default='species_icons/default-icon.png', upload_to='species_icons')),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='resource.Species')),
                ('cDNA_data', models.FileField(blank=True, upload_to='data_sets/')),
                ('siRNA_data', models.FileField(blank=True, upload_to='data_sets/')),
                ('ncRNA_data', models.FileField(blank=True, upload_to='data_sets/')),
                ('genome_data', models.FileField(blank=True, upload_to='data_sets/')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('genus', 'species_name')},
        ),
        migrations.AddField(
            model_name='sequence',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.Species'),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('chromosome', 'start', 'sequence_id', 'development_stage', 'target_gene')},
        ),
    ]
